### ISSUE TITLE
Need to support equivalent output format to existing generator formats

### ISSUE THREAD

**Issue by luketpickering** [luketpickering/HepMCNuEvtTools#1]
Here I am mostly thinking that e.g. NuWro writes out multiple final-state particle vectors, pre-FSI and post-FSI (and others), but it doesn't write out the entire cascade. The way that I was going to support this was having multiple unconnected vertices in an event with different status codes. But maybe this is an abuse of the vertex status code. Can instead hack it up as all of the pre-FSI hadrons leave the hard scatter vertex and end at a secondary vertex, which has the post-FSI/nuclear-leaving particle stack. This is also a bit of abuse, but if the cascade isn't stored by current format, there is no way to track a given pre-FSI particle through to post-FSI. We could also just ignore this and only put nuclear-leaving particles in existing generators until they change their information to support our standard, but I feel that if we support exact two-way conversion then we are more likely to gain early traction.

**Comment by jxi24** [comment]
I think the second option is better. The particles before the cascade have a status code corresponding to an intermediate particle. These then all enter a vertex, and the outgoing particles are the final state particles. Those are labeled with a final state status code. We can then try to encourage NuWro to include more information on their cascade. Additionally, the requirement that sufficient information to reproduce the events should give some information on how to do reweighting. With the pre-FSI particles, one could always interface to other codes for the cascade that include the entire history.
